#spring:
#  application:
#    name: store
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: config-server
#      retry:
#        initialInterval: 2000
#        multiplier: 1.5
#        maxInterval: 60000
#        maxAttempts: 100
#
#eureka:
#  client:
#    service-url:
#      enabled: true
#      fetch-registry: true
#      register-with-eureka: true
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
#  instance:
#    lease-renewal-interval-in-seconds: 10

server:
  port: 8001
  servlet:
    context-path: /api/v1/

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: store
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: gernika54

springdoc:
  api-docs:
    enabled: true
  paths-to-match: /store/**