server:
  port: 8001
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: store
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: postgres
    password: gernika54
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      enabled: true
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10