stages:
  - login
  - build

job:login:
  image: docker:latest
  stage: login
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  only:
    -  chore/docker

job:build:base:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t "${CI_PROJECT_NAME}-base:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" .
    # - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-0.1.${CI_JOB_ID}" --build-arg SERVICE_NAME=eureka-server .
  only:
    -  chore/docker