variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djansi.force=true"
  MAVEN_CLI_OPTS: "--errors --fail-at-end --show-version -Dstyle.color=always"
cache:
  key: mavenrepo
  paths:
    - ./.m2/repository/

stages:
  - login
  - build

# OK
# job:login:
#   image: docker:latest
#   stage: login
#   services:
#     - docker:dind
#   script:
#     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
#   only:
#     -  chore/docker

job:build:dependencies:
  stage: build
  image: maven:3.8.3-amazoncorretto-17
  script:
    # - mvn $MAVEN_CLI_OPTS package -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never
  only:
    -  chore/docker

job:build:tier0:
  stage: build
  image: maven:3.8.3-amazoncorretto-17
  script:
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:rabbitMQ
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:rabbitMQ -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:eureka-server
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:eureka-server -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:gateway
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:gateway -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:customer
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:customer -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:store
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:store -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:product
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:product -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:customisation
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:customisation -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:subscription
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:subscription -DskipTests
    - mvn $MAVEN_CLI_OPTS verify --fail-never -pl com.diy:ticket
    - mvn $MAVEN_CLI_OPTS package -pl com.diy:ticket -DskipTests
  only:
    -  chore/docker
  parallel: 4
  needs:
    - job:build:dependencies
  artifacts:
    paths:
      - target/*.jar


# com.diy:clients
# com.diy:notification
# - mvn package -pl com.diy:notification --also-make
# com.diy:order
# - mvn package -pl com.diy:order --also-make
# com.diy:authentication
# - mvn package -pl com.diy:authentication --also-make



# COPY --from=build-rabbitmq ${SRC}/services/infra/rabbitmq/target/rabbitmq-1.0-SNAPSHOT.jar /target/rabbitmq-1.0-SNAPSHOT.jar
# COPY --from=build-eureka-server ${SRC}/services/infra/eureka-server/target/eureka-server-1.0-SNAPSHOT.jar /target/eureka-server-1.0-SNAPSHOT.jar
# COPY --from=build-gateway ${SRC}/services/infra/gateway/target/gateway-1.0-SNAPSHOT.jar /target/gateway-1.0-SNAPSHOT.jar
# COPY --from=build-customer ${SRC}/services/core/customer/target/customer-1.0-SNAPSHOT-exec.jar /target/customer-1.0-SNAPSHOT.jar
# COPY --from=build-store ${SRC}/services/core/store/target/store-1.0-SNAPSHOT-exec.jar /target/store-1.0-SNAPSHOT.jar
# COPY --from=build-product ${SRC}/services/core/product/target/product-1.0-SNAPSHOT.jar /target/product-1.0-SNAPSHOT.jar
# COPY --from=build-customisation ${SRC}/services/back-office/customisation/target/customisation-1.0-SNAPSHOT.jar /target/customisation-1.0-SNAPSHOT.jar
# COPY --from=build-subscription ${SRC}/services/back-office/subscription/target/subscription-1.0-SNAPSHOT.jar /target/subscription-1.0-SNAPSHOT.jar
# COPY --from=build-ticket ${SRC}/services/back-office/ticket/target/ticket-1.0-SNAPSHOT.jar /target/ticket-1.0-SNAPSHOT.jar
# COPY --from=build-notification ${SRC}/services/core/notification/target/notification-1.0-SNAPSHOT.jar /target/notification-1.0-SNAPSHOT.jar
# COPY --from=build-order ${SRC}/services/core/order/target/order-1.0-SNAPSHOT.jar /target/order-1.0-SNAPSHOT.jar
# COPY --from=build-authentication ${SRC}/services/core/authentication/target/authentication-1.0-SNAPSHOT.jar /target/authentication-1.0-SNAPSHOT.jar
