---
services:

  service-discovery:
    image: ${CONTAINER_REGISTRY}/cande-eureka-server:latest
    ports:
      - 8761:8761

  service-gateway:
    image: ${CONTAINER_REGISTRY}/cande-gateway:latest
    ports:
      - 8080:8080

  backing-db:
    image: ${CONTAINER_REGISTRY}/cande-db:latest

  backing-mq:
    image: rabbitmq:3.9.11-management-alpine

  service-authentication:
    image: ${CONTAINER_REGISTRY}/cande-authentication:latest

  service-customer:
    image: ${CONTAINER_REGISTRY}/cande-customer:latest

  service-notification:
    image: ${CONTAINER_REGISTRY}/cande-notification:latest

  service-order:
    image: ${CONTAINER_REGISTRY}/cande-order:latest

  service-product:
    image: ${CONTAINER_REGISTRY}/cande-product:latest

  service-store:
    image: ${CONTAINER_REGISTRY}/cande-store:latest

  service-customisation:
    image: ${CONTAINER_REGISTRY}/cande-customisation:latest

  # service-payment:
  #   image: ${CONTAINER_REGISTRY}/cande-payment:latest

  service-subscription:
    image: ${CONTAINER_REGISTRY}/cande-subscription:latest

  service-ticket:
    image: ${CONTAINER_REGISTRY}/cande-ticket:latest

  test-integration:
    image: ${CONTAINER_REGISTRY}/cande-integration:latest
