---
services:

  service-discovery:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - ${EUREKA_PORT:-8761}:8761

  service-gateway:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - ${GATEWAY_PORT:-8080}:8080

  backing-db:
    build:
      context: ./db
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  backing-mq:
    ports:
      - 5672:5672
      - 15672:15672

  service-authentication:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-customer:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-notification:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-order:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-product:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-store:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-customisation:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-payment:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-subscription:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  service-ticket:
    build:
      dockerfile: Dockerfile.dev
  #   ports:
  #     - XXXX:XXXX

  test-integration:
    build:
      context: ./integration
