---
services:

  # service-discovery:
  #   build:
  #     args:
  #       SERVICE_NAME: eureka-server
  #     context: .
  #     dockerfile: Dockerfile.ms
  #   container_name: eureka-server
  #   # environment:
  #   #   SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  #   #   TZ: ${TZ:-Europe/Paris}
  #   ports:
  #     - ${SRV_EUREKA:-8761}:8761

  # service-config:
  #   build:
  #     args:
  #       SERVICE_NAME: config-server
  #     context: ./services/config/config-server
  #   container_name: config-server
  #   # environment:
  #   #   EUREKA_URI: ${EUREKA_URI}
  #   #   SPRING_PROFILES_ACTIVE: native,${SPRING_PROFILES_ACTIVE}
  #   #   TZ: ${TZ}
  #   depends_on:
  #     - service-discovery
  #   ports:
  #     - ${SRV_CONFIG:-8888}:8888

  postgres:
    build:
      context: ./external/db
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: ${PGDATA:-/data/postgres}
      TZ: ${TZ:-Europe/Paris}
      PGTZ: ${TZ:-Europe/Paris}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    environment:
      TZ: ${TZ:-Europe/Paris}
    ports:
      - 5672:5672
      - 15672:15672
