---
services:

  # INFRA
  service-discovery:
    build:
      args:
        SERVICE_NAME: eureka-server
      dockerfile: Dockerfile.bak
    container_name: eureka-server
    ports:
      - ${EUREKA_PORT:-8080}:8761

  service-gateway:
    build:
      args:
        SERVICE_NAME: gateway
      dockerfile: Dockerfile.bak
    container_name: gateway
    depends_on:
      - service-discovery
    ports:
      - ${GATEWAY_PORT:-80}:8080

  postgres:
    build:
      context: ./db
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /data/postgres
      TZ: ${TZ:-Europe/Paris}
      PGTZ: ${TZ:-Europe/Paris}
    # ports:
    #   - ${POSTGRES_PORT:-5432}:5432

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    environment:
      TZ: ${TZ:-Europe/Paris}}
    # ports:
    #   - 5672:5672
    #   - 15672:15672

  # CORE
  service-authentication:
    build:
      args:
        SERVICE_NAME: authentication
      dockerfile: Dockerfile.bak
    container_name: authentication
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  service-customer:
    build:
      args:
        SERVICE_NAME: customer
      dockerfile: Dockerfile.bak
    container_name: customer
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  # service-notification:
  #   build:
  #     args:
  #       SERVICE_NAME: notification
  #   container_name: notification
  #   environment:
  #     DB_URI: ${DB_URI}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     TWILIO_SID: ${TWILIO_SID}
  #     TWILIO_TOKEN: ${TWILIO_TOKEN}
  #     TWILIO_NUM: ${TWILIO_NUM}
  #     RABBITMQ_URI: ${RABBITMQ_URI}
  #   depends_on:
  #     - service-gateway
  #     - postgres
  #     - rabbitmq

  service-order:
    build:
      args:
        SERVICE_NAME: order
      dockerfile: Dockerfile.bak
    container_name: order
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RABBITMQ_URI: ${RABBITMQ_URI}
    depends_on:
      - service-gateway
      - postgres
      - rabbitmq

  service-product:
    build:
      args:
        SERVICE_NAME: product
      dockerfile: Dockerfile.bak
    container_name: product
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  service-store:
    build:
      args:
        SERVICE_NAME: store
      dockerfile: Dockerfile.bak
    container_name: store
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  # BACK-OFFICE
  service-customisation:
    build:
      args:
        SERVICE_NAME: customisation
      dockerfile: Dockerfile.bak
    container_name: customisation
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  # service-payment:
  #   build:
  #     args:
  #       SERVICE_NAME: payment
  #   container_name: payment
  #   depends_on:
  #     - service-gateway
  #     - postgres

  service-subscription:
    build:
      args:
        SERVICE_NAME: subscription
      dockerfile: Dockerfile.bak
    container_name: subscription
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  service-ticket:
    build:
      args:
        SERVICE_NAME: ticket
      dockerfile: Dockerfile.bak
    container_name: ticket
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - postgres

  service-integration:
    build:
      context: ./integration
      args:
        DOCKER_IMAGE: python:3.11.2-slim-bullseye
        PROJECT_NAME: integration
    container_name: integration
    environment:
      STAGE: $STAGE
    depends_on:
      - service-authentication
