---
services:

  service-discovery:
    build:
      args:
        SERVICE_NAME: eureka-server
      context: .
      dockerfile: Dockerfile.ms
    container_name: eureka-server
    ports:
      - 8080:8761

  service-config:
    build:
      args:
        SERVICE_NAME: config-server
      context: ./services/infra/config-server
    container_name: config-server
    depends_on:
      - service-discovery

  service-gateway:
    build:
      args:
        SERVICE_NAME: gateway
      context: .
      dockerfile: Dockerfile.ms
    container_name: gateway
    depends_on:
      - service-config
    ports:
      - 80:8080

  # service-authentication:
  #   build:
  #     args:
  #       SERVICE_NAME: authentication
  #     context: .
  #     dockerfile: Dockerfile.ms
  #   container_name: authentication
  #   environment:
  #     DB_URI: ${DB_URI}/authentication
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #   depends_on:
  #     - service-gateway

  # service-customer:
  #   build:
  #     args:
  #       SERVICE_NAME: customer
  #     context: .
  #     dockerfile: Dockerfile.ms
  #   networks:
  #     - spring
  #   # depends_on:
  #   #   - eureka

  # service-order:
  #   build:
  #     args:
  #       SERVICE_NAME: order
  #     context: .
  #     dockerfile: Dockerfile.ms
  #   networks:
  #     - spring
  #   # depends_on:
  #   #   - eureka

  # postgres:
  #   build:
  #     context: ./db
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS}
  #     PGDATA: /data/postgres
  #     TZ: ${TZ}
  #     PGTZ: ${TZ}
  #   ports:
  #     - ${POSTGRES_PORT:-5432}:5432

  # rabbitmq:
  #   image: rabbitmq:3.9.11-management-alpine
  #   container_name: rabbitmq
  #   environment:
  #     TZ: ${TZ}
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

  # service-notification:
  #   build:
  #     args:
  #       SERVICE_NAME: notification
  #     context: .
  #     dockerfile: Dockerfile.ms
  #   container_name: notification
  #   environment:
  #     RABBITMQ_URI: ${RABBITMQ_URI}
  #     DB_URI: ${DB_URI}/customer
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  #     TWILIO_SID: ${TWILIO_SID}
  #     TWILIO_TOKEN: ${TWILIO_TOKEN}
  #     TWILIO_NUM: ${TWILIO_NUM}
  #     TZ: ${TZ}
  #   networks:
  #     - net-ms
  #     - net-postgres
  #     - net-rabbitmq
  #   depends_on:
  #     - service-config
  #     - postgres
  #     - rabbitmq
