---
services:

  # INFRA
  service-discovery:
    image: ${CONTAINER_REGISTRY}/cande-eureka-server:latest
    container_name: eureka-server
    ports:
      - ${EUREKA_PORT:-8080}:8761

  service-gateway:
    image: ${CONTAINER_REGISTRY}/cande-gateway:latest
    container_name: gateway
    depends_on:
      - service-discovery
    ports:
      - ${GATEWAY_PORT:-80}:8080

  backing-db:
    image: ${CONTAINER_REGISTRY}/cande-db:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  backing-mq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    environment:
      TZ: ${TZ:-Europe/Paris}

  # CORE
  service-authentication:
    image: ${CONTAINER_REGISTRY}/cande-authentication:latest
    container_name: authentication
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  service-customer:
    image: ${CONTAINER_REGISTRY}/cande-customer:latest
    container_name: customer
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  service-notification:
    image: ${CONTAINER_REGISTRY}/cande-notification:latest
    container_name: notification
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_TOKEN: ${TWILIO_TOKEN}
      TWILIO_NUM: ${TWILIO_NUM}
      RABBITMQ_URI: ${RABBITMQ_URI}
    depends_on:
      - service-gateway
      - backing-mq
      - backing-db

  service-order:
    image: ${CONTAINER_REGISTRY}/cande-order:latest
    container_name: order
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RABBITMQ_URI: ${RABBITMQ_URI}
    depends_on:
      - service-gateway
      - backing-mq
      - backing-db

  service-product:
    image: ${CONTAINER_REGISTRY}/cande-product:latest
    container_name: product
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  service-store:
    image: ${CONTAINER_REGISTRY}/cande-store:latest
    container_name: store
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  # BACK-OFFICE
  service-customisation:
    image: ${CONTAINER_REGISTRY}/cande-customisation:latest
    container_name: customisation
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  # service-payment:
  #   build:
  #     args:
  #       SERVICE_NAME: payment
  #   container_name: payment
  #   depends_on:
  #     - service-gateway
  #     - postgres

  service-subscription:
    image: ${CONTAINER_REGISTRY}/cande-subscription:latest
    container_name: subscription
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  service-ticket:
    image: ${CONTAINER_REGISTRY}/cande-ticket:latest
    container_name: ticket
    environment:
      DB_URI: ${DB_URI}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - service-gateway
      - backing-db

  test-integration:
    image: ${CONTAINER_REGISTRY}/cande-integration:latest
    container_name: integration
    environment:
      STAGE: staging
    depends_on:
      - service-authentication
