FROM yulquen/cande-builder:latest
ARG SERVICE_NAME
COPY ./artifacts/${SERVICE_NAME}-1.0-SNAPSHOT.jar /usr/local/bin/artifact.jar
ENTRYPOINT [ "/jre/bin/java", "-jar", "/usr/local/bin/artifact.jar" ]


EXPOSE 8080
