openapi: 3.0.1
info:
  title: MNS
  description: 'MNS subscription'
  version: 1.0.0
servers:
  - url: http://localhost:8004/com/diy/subscription/v1
tags:
  - name: subscription
    description: Everything about subscriptions
paths:
  /subscription/subscriptionsType:
    get:
      tags:
        - subscription
      summary: Find all subscription type
      description: Find all subscription type
      operationId: findAllSubscriptionType
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionType'
        404:
          description: Invalid request
          content: { }

  /subscription/{storeId}:
    get:
      tags:
        - subscription
      summary: Get subscription for a given store
      description: Create a subscription for a given store
      operationId: GetStoreSubscription
      parameters:
        - name: storeId
          in: path
          description: Store ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        404:
          description: Invalid request
          content: { }

  /subscription/save:
    post:
      tags:
        - subscription
      summary: Update a subscription for a given store
      description: Update a subscription for a given store
      operationId: updateStoreSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveSubscription'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        404:
          description: Invalid request
          content: { }
    put:
      tags:
        - subscription
      summary: Create a subscription for a given store
      description: Create a subscription for a given store
      operationId: createStoreSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveSubscription'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        404:
          description: Invalid request
          content: { }

components:
  schemas:
    Subscription:
      type: object
      properties:
        subscriptionId:
          type: integer
          format: int64
        storeId:
          type: integer
          format: int64
        dateStart:
          type: string
        dateEnd:
          type: string
        paymentType:
          type: string
        subscriptionType:
          $ref: '#/components/schemas/SubscriptionType'

    SubscriptionType:
      type: object
      properties:
        subscriptionTypeId:
          type: integer
          format: int64
        name:
          type: string
        turnover:
          type: number
          format: int64
        support:
          type: string
        price:
          type: number

    SaveSubscription:
      type: object
      properties:
        subscriptionId:
          type: integer
          format: int64
        storeId:
          type: integer
          format: int64
        dateStart:
          type: string
        dateEnd:
          type: string
        paymentType:
          type: string
        subscriptionType:
          $ref: '#/components/schemas/SubscriptionType'