server:
  port: 8000
  servlet:
    context-path: /api/v1/

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    # url: ${env.DB_URI}
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: gernika54
  application:
    name: authentication

springdoc:
  swagger-ui:
    path: /swagger-ui.html
