spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: gernika54
server:
  port: 8008


