spring:
  application:
    name: store
  jackson:
    time-zone: Europe/Berlin
    date-format: yyyy-MM-dd
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: gernika54
server:
  port: 8001
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: api-docs

