spring:
  application:
    name: store
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: gernika54
server:
  port: 8001
