server:
  port: 8080
  servlet:
    context-path: /api/v1/notification/

spring:
  rabbitmq:
    addresses: rabbitmq:5672
    # addresses: ${RABBITMQ_URI}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/notification
    username: postgres
    password: gernika54
    # url: ${DB_URI}
    # username: ${DB_USER}
    # password: ${DB_PASS}

twilio:
  account_sid: ${TWILIO_SID}
  auth_token: ${TWILIO_TOKEN}
  trial_number: ${TWILIO_NUM}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key