server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: customer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:${DB_URI}/${spring.application.name}
    username: ${DB_USER}
    password: ${DB_PASS}

eureka:
  client:
    service-url:
      enabled: true
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI}
  instance:
    lease-renewal-interval-in-seconds: ${LEASE_RENEWAL_INTERVAL:10}
