server:
  port: 8000
  servlet:
    context-path: /api/v1/authentication/

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    # url: ${env.DB_URI}
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: gernika54

springdoc:
  swagger-ui:
    path: /swagger-ui.html
