server:
  port: 8080
  servlet:
    context-path: /api/v1/authentication/

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: @db.uri@
    username: @db.user@
    password: @db.pass@

springdoc:
  swagger-ui:
    path: /swagger-ui.html
