server:
  port: 8080
  servlet:
    context-path: /api/v1/customisation/

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASS}
