server:
  port: 8007
  servlet:
    context-path: /api/v1/notification/

spring:
  rabbitmq:
    addresses: localhost:5672
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: gernika54

twilio:
  account_sid: AC34f91f7b1d9b35144662cfff0e7c07be
  auth_token: 90764088f400e64009b4373d06328f58
  trial_number: +15005550006

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key