spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: provisioningService
          uri: http://localhost:8090
          predicates:
          - Path=/bosch/iot/diy/connected-charger/v1/devices/**


server:
  port: 8080
  ssl:
    enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true