spring:
  application:
    name: configuration-service
    cloud:
      config:
        server:
          git:
            uri: C://dev/MNS/cloud-config

server:
  port: 8081
  tomcat:
    accesslog:
      basedir: C://dev/MNS/logs
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS