openapi: 3.0.1
info:
  title: MNS
  description: 'MNS store'
  version: 1.0.0
servers:
  - url: http://localhost:8001/com/diy/store/v1
tags:
  - name: store
    description: Everything about store, dixit the merchant.
paths:
  /stores:
    get:
      tags:
        - store
      summary: Find all stores
      description: Get all stores
      operationId: findStores
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'
        404:
          description: Invalid request
          content: {}

components:
  schemas:
    Store:
      type: object
      properties:
        storeId:
          type: integer
        siret:
          type: string
        sector:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        subscriptionId:
          type: integer
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'

    Address:
      type: object
      properties:
        addressId:
          type: integer
        city:
          type: string
        postalCode:
          type: string
        complement:
          type: string
        streetNumber:
          type: string
        streetName:
          type: string