openapi: 3.0.1
info:
  title: MNS
  description: 'MNS store'
  version: 1.0.0
servers:
  - url: http://localhost:8001/com/diy/store/v1
tags:
  - name: store
    description: Everything about store, dixit the merchant.
paths:
  /stores/{size}/{page}/{sortby}/{ascending}:
    get:
      tags:
        - store
      summary: Find all stores
      description: Get all stores
      operationId: findStores
      parameters:
        - name: size
          in: path
          description: The size of the array wanted, usually no more than 50
          required: true
          schema:
            type: integer
        - name: page
          in: path
          description: The page number to know where to put sql cursor on. Pages start at index 0
          required: true
          schema:
            type: integer
        - name: sortby
          in: path
          description: The name of the field to sort the result by
          required: true
          schema:
            type: string
        - name: ascending
          in: path
          description: Noting if the sorting is ascending or not
          required: true
          schema:
            type: boolean
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'
        404:
          description: Invalid request
          content: {}

  /store/{storeId}:
    get:
      tags:
        - store
      summary: Find a specific store with its ID
      description: Get a store by id
      operationId: findStoreById
      parameters:
          - name: storeId
            in: path
            description: Store ID
            required: true
            schema:
                type: integer
                format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        404:
          description: Invalid request
          content: {}

    delete:
      tags:
        - store
      summary: Delete a store
      description: Delete a store by ID with all its dependencies in other microservices
      operationId: deleteStoreById
      parameters:
        - name: storeId
          in: path
          description: Store ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string

        404:
          description: Invalid request
          content: { }

  /store:
    post:
      tags:
        - store
      summary: Create or update a store
      description: Get a store object and potentially an address object nested, from the body
      operationId: saveStore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Store'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        404:
          description: Invalid request
          content: {}


components:
  schemas:
    Store:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
        siret:
          type: string
        storeName:
          type: string
        sector:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        subscriptionId:
          type: integer
          format: int64
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'

    Address:
      type: object
      properties:
        addressId:
          type: integer
          format: int64
        city:
          type: string
        postalCode:
          type: string
        complement:
          type: string
        streetNumber:
          type: string
        streetName:
          type: string