openapi: 3.0.1
info:
  title: MNS
  description: 'MNS customer'
  version: 1.0.0
servers:
  - url: http://localhost:8006/com/diy/customer/v1
tags:
  - name: customer
    description: Everything about customers
paths:
  /path:

components:
  schemas:
