server:
  port: 8080
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: notification
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:${DB_URI}/${spring.application.name}
    username: ${DB_USER}
    password: ${DB_PASS}
  rabbitmq:
    addresses: ${RABBITMQ_URI}

eureka:
  client:
    service-url:
      enabled: true
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI}
  instance:
    lease-renewal-interval-in-seconds: ${LEASE_RENEWAL_INTERVAL:10}

twilio:
  account_sid: ${TWILIO_SID}
  auth_token: ${TWILIO_TOKEN}
  trial_number: ${TWILIO_NUM}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key
