spring:
  application:
    name: notification
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: gernika54
server:
  port: 8007
