server:
  port: 8080
  servlet:
    context-path: /api/v1/order/

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/order
    username: postgres
    password: gernika54
    # url: ${DB_URI}
    # username: ${DB_USER}
    # password: ${DB_PASS}
  rabbitmq:
    addresses: rabbitmq:5672
    # addresses: ${RABBITMQ_URI}