spring:
  application:
    name: api-gateway

#  zipkin:
#    base-url: http://localhost:9411

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "**"
            allowedHeaders:
              - content-type
              - Authorization
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowCredentials: true
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**

        - id: customisation
          uri: lb://CUSTOMISATION
          predicates:
            - Path=/api/v1/customisation/**

        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payment/**

        - id: subscription
          uri: lb://SUBSCRIPTION
          predicates:
            - Path=/api/v1/subscription/**

        - id: ticket
          uri: lb://TICKET
          predicates:
            - Path=/api/v1/ticket/**

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/product/**

        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**

        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/order/**

        - id: store
          uri: lb://STORE
          predicates:
            - Path=/api/v1/store/**

        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/v1/authentication/**
#          filters:
#            - AuthorizationFilter

server:
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
