openapi: 3.0.1
info:
  title: MNS
  description: 'MNS customisation'
  version: 1.0.0
servers:
  - url: http://localhost:8002/com/diy/customisation/v1
tags:
  - name: customisation
    description: Everything about store's customisation
paths:
  /path:
#
#components:
#  schemas:
