#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE authentication;
  GRANT ALL PRIVILEGES ON DATABASE authentication TO $POSTGRES_USER;

EOSQL
