#!/bin/sh
set -e
export PGPASSWORD="$POSTGRES_PASSWORD";
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE authentication;
  GRANT ALL PRIVILEGES ON DATABASE authentication TO $POSTGRES_USER;
  CREATE DATABASE store;
  GRANT ALL PRIVILEGES ON DATABASE store TO $POSTGRES_USER;
  CREATE DATABASE customisation;
  GRANT ALL PRIVILEGES ON DATABASE customisation TO $POSTGRES_USER;
  CREATE DATABASE payment;
  GRANT ALL PRIVILEGES ON DATABASE payment TO $POSTGRES_USER;
  CREATE DATABASE subscription;
  GRANT ALL PRIVILEGES ON DATABASE subscription TO $POSTGRES_USER;
  CREATE DATABASE ticket;
  GRANT ALL PRIVILEGES ON DATABASE ticket TO $POSTGRES_USER;
  CREATE DATABASE customer;
  GRANT ALL PRIVILEGES ON DATABASE customer TO $POSTGRES_USER;
  CREATE DATABASE notification;
  GRANT ALL PRIVILEGES ON DATABASE notification TO $POSTGRES_USER;
  CREATE DATABASE orders;
  GRANT ALL PRIVILEGES ON DATABASE orders TO $POSTGRES_USER;
  CREATE DATABASE product;
  GRANT ALL PRIVILEGES ON DATABASE product TO $POSTGRES_USER;
EOSQL
