server:
  port: 8761
  ssl:
    enabled: false

spring:
  application:
    name: eureka-server
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
