server:
  port: 8761
  ssl:
    enabled: false

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${spring.application.name}
    leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAL:10}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
