spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/subscription
    username: postgres
    password: gernika54
server:
  port: 8080
  servlet:
    context-path: /api/v1/