server:
  port: 8080
  servlet:
    context-path: /api/v1/customisation/

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/customisation
    username: postgres
    password: gernika54
