openapi: 3.0.1
info:
  title: MNS
  description: 'MNS product'
  version: 1.0.0
servers:
  - url: http://localhost:8009/com/diy/product/v1
tags:
  - name: product
    description: Everything about products
paths:

  /product/product/all/{storeId}:
    get:
      tags:
        - product
      summary: Find all product according to its store id
      description: Get all product related to a store
      operationId: getAllProductByStoreId
      parameters:
        - name: storeId
          in: path
          description: Store ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        404:
          description: Invalid request
          content: { }

  /product/product/{productId}:
    get:
      tags:
        - product
      summary: Find a specific product with its ID
      description: Get a product by id
      operationId: findProductById
      parameters:
        - name: productId
          in: path
          description: Product ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductWithoutCategory'
        404:
          description: Invalid request
          content: { }

    delete:
      tags:
        - product
      summary: Delete a product
      description: Delete a product by ID
      operationId: deleteProductById
      parameters:
        - name: productId
          in: path
          description: Product ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string

        404:
          description: Invalid request
          content: { }

  /product/product/save:
    post:
      tags:
        - product
      summary: Update a product
      description: Get a product object and potentially a category object nested, from the body
      operationId: updateProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductWithoutCategory'
        404:
          description: Invalid request
          content: { }
    put:
      tags:
        - product
      summary: Create a product
      description: Get a product object and potentially a category object nested, from the body
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductWithoutCategory'
        404:
          description: Invalid request
          content: { }

  /product/categories/{storeId}:
    get:
      tags:
        - category
      summary: Find all categories according to its store id
      description: Get all categories related to a store
      operationId: getAllCategoryByStoreId
      parameters:
        - name: storeId
          in: path
          description: Store ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryWithoutProduct'
        404:
          description: Invalid request
          content: { }

  /product/category/{categoryId}:
    get:
      tags:
        - category
      summary: find a category by ID and all its product associated
      description: Get a single category and all its product associated. According to a specific store id
      operationId: getCategoryAndItsProductByStoreId
      parameters:
        - name: categoryId
          in: path
          description: Store ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryWithProduct'
        404:
          description: Invalid request
          content: { }

    delete:
      tags:
        - category
      summary: Delete a category
      description: Delete a category by ID
      operationId: deleteCategoryById
      parameters:
        - name: categoryId
          in: path
          description: store ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string

        404:
          description: Invalid request
          content: { }

  /product/category/save:
    post:
      tags:
        - category
      summary: Update a category
      description: Get a category object and update it
      operationId: updateCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryWithoutProduct'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryWithoutProduct'
        404:
          description: Invalid request
          content: { }
    put:
      tags:
        - category
      summary: Create a category
      description: Get a category object and create it
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryWithoutProduct'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryWithoutProduct'
        404:
          description: Invalid request
          content: { }

components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: float

        description:
          type: string
        weight:
          type: number
          format: float

        height:
          type: number
          format: float

        photo:
          type: string
        availableInStore:
          type: boolean
        storeId:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'

    ProductWithoutCategory:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: float
        description:
          type: string
        weight:
          type: number
          format: float
        height:
          type: number
          format: float
        photo:
          type: string
        availableInStore:
          type: boolean
        storeId:
          type: integer
          format: int64

    Category:
      type: object
      properties:
        categoryId:
          type: integer
          format: int64
        name:
          type: string
        storeId:
          type: integer
          format: int64
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'

    CategoryWithoutProduct:
      type: object
      properties:
        categoryId:
          type: integer
          format: int64
        name:
          type: string
        storeId:
          type: integer
          format: int64

    CategoryWithProduct:
      type: object
      properties:
        categoryId:
          type: integer
          format: int64
        name:
          type: string
        storeId:
          type: integer
          format: int64
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductWithoutCategory'

