server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      # override-system-properties: true
      server:
        native:
          # search-locations: "file://${CONFIG_DIR:@project-root@/src/main/resources/config}"
          search-locations: classpath:/config/{application}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
      fetch-registry: true
      register-with-eureka: true
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 25
    lease-expiration-duration-in-seconds: 10
